version: "3.9"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    restart: always
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: localhost
    expose:
      - "3000"
    depends_on:
      - db
    networks: 
      - node-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
    - 80:80
    depends_on:
      - api
    networks: 
      - node-network

  db:
    image: postgres:14.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nginx_node_db_development
    expose:
      - "5432"
    restart: always
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge